version: '2'

services:
  mongodb:
    # https://github.com/bitnami/bitnami-docker-mongodb
    image: docker.io/bitnami/mongodb:4.4.11-debian-10-r12
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_ROOT_USER: ${MONGODB__ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB__ROOT_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"

  postgresql:
    # https://github.com/bitnami/bitnami-docker-postgresql
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL__POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRESQL__USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL__PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"

  nfs:
    # https://hub.docker.com/r/erichough/nfs-server
    image: erichough/nfs-server
    cap_add:
      - SYS_ADMIN
    ports:
      - "2049:2049"
      - "2049:2049/udp"
      - "111:111"
      - "111:111/udp"
      - "32765:32765"
      - "32765:32765/udp"
      - "32767:32767"
      - "32767:32767/udp"
    volumes:
      - './exports.txt:/etc/exports:ro'
      - '/data:/data:rw'

  rabbitmq:
    # https://github.com/bitnami/bitnami-docker-rabbitmq
    image: docker.io/bitnami/rabbitmq:3.9.16-debian-10-r0
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_SECURE_PASSWORD: "yes"
      RABBITMQ_LOGS: "-"
      RABBITMQ_USERNAME: ${RABBITMQ__USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ__PASSWORD}
      RABBITMQ_PLUGINS: rabbitmq_management
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

  redis:
    # https://github.com/bitnami/bitnami-docker-redis
    image: docker.io/bitnami/redis:6.2.6-debian-10-r97
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ${REDIS__PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  mongodb_data:
    driver: local
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

