version: '2'

services:
  mongodb:
    image: docker.io/mongo:8.0.11
    restart: ${RESTART_POLICY:-no}
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgresql:
    image: docker.io/postgres:17.4-alpine3.21
    restart: ${RESTART_POLICY:-no}
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # If the external services are being run on the same server as KubeAdm then
  # this section can remain as commented out.
#  nfs:
#    # https://hub.docker.com/r/erichough/nfs-server
#    image: erichough/nfs-server
#    cap_add:
#      - SYS_ADMIN
#    ports:
#      - "2049:2049"
#      - "2049:2049/udp"
#      - "111:111"
#      - "111:111/udp"
#      - "32765:32765"
#      - "32765:32765/udp"
#      - "32767:32767"
#      - "32767:32767/udp"
#    volumes:
#      - './exports.txt:/etc/exports:ro'
#      - '/data:/data:rw'
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"

  rabbitmq:
    image: docker.io/rabbitmq:4.1.1
    restart: ${RESTART_POLICY:-no}
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_SECURE_PASSWORD: "yes"
      RABBITMQ_LOGS: "-"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_PLUGINS: rabbitmq_management
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: 2GB
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/mnesia'
      - './config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: docker.io/redis:8.0.3
    restart: ${RESTART_POLICY:-no}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

