version: '2'

services:
  mongodb:
    # https://github.com/bitnami/bitnami-docker-mongodb
    image: docker.io/bitnami/mongodb:8.0.6-debian-12-r3
    restart: ${RESTART_POLICY:-no}
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_ROOT_USER: ${MONGODB__ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB__ROOT_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgresql:
    # https://github.com/bitnami/bitnami-docker-postgresql
    image: docker.io/bitnami/postgresql:17.2.0-debian-12-r12
    restart: ${RESTART_POLICY:-no}
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL__POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRESQL__USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL__PASSWORD}
      ALLOW_EMPTY_PASSWORD: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # If the external services are being run on the same server as KubeAdm then
  # this section can remain as commented out.
#  nfs:
#    # https://hub.docker.com/r/erichough/nfs-server
#    image: erichough/nfs-server
#    cap_add:
#      - SYS_ADMIN
#    ports:
#      - "2049:2049"
#      - "2049:2049/udp"
#      - "111:111"
#      - "111:111/udp"
#      - "32765:32765"
#      - "32765:32765/udp"
#      - "32767:32767"
#      - "32767:32767/udp"
#    volumes:
#      - './exports.txt:/etc/exports:ro'
#      - '/data:/data:rw'
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"

  rabbitmq:
    # https://github.com/bitnami/bitnami-docker-rabbitmq
    image: docker.io/bitnami/rabbitmq:4.0.8-debian-12-r2
    restart: ${RESTART_POLICY:-no}
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_SECURE_PASSWORD: "yes"
      RABBITMQ_LOGS: "-"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}
      RABBITMQ_PLUGINS: rabbitmq_management
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: 2GB
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
      - './rabbitmq.conf:/bitnami/rabbitmq/conf/rabbitmq.conf'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    # https://github.com/bitnami/bitnami-docker-redis
    image: docker.io/bitnami/redis:7.4.1-debian-12-r3
    restart: ${RESTART_POLICY:-no}
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ${REDIS__PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

